# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tela_Inicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 904)
        MainWindow.setStyleSheet("font: \"Arial\";\n"
"background-color: rgb(65, 197, 197);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 50, 161, 191))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Desktop/Pufferfish_29_JE4_BE1.webp"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(420, 230, 281, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_cadastroPaciente = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cadastroPaciente.setGeometry(QtCore.QRect(200, 570, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_cadastroPaciente.setFont(font)
        self.pushButton_cadastroPaciente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_cadastroPaciente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_cadastroPaciente.setObjectName("pushButton_cadastroPaciente")
        self.pushButton_controlDiteta = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_controlDiteta.setGeometry(QtCore.QRect(400, 570, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_controlDiteta.setFont(font)
        self.pushButton_controlDiteta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_controlDiteta.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_controlDiteta.setObjectName("pushButton_controlDiteta")
        self.pushButton_registroDieta = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_registroDieta.setGeometry(QtCore.QRect(590, 570, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_registroDieta.setFont(font)
        self.pushButton_registroDieta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_registroDieta.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_registroDieta.setObjectName("pushButton_registroDieta")
        self.pushButton_agenda = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_agenda.setGeometry(QtCore.QRect(780, 570, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_agenda.setFont(font)
        self.pushButton_agenda.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_agenda.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_agenda.setObjectName("pushButton_agenda")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Baiacu Nutricionista"))
        self.pushButton_cadastroPaciente.setText(_translate("MainWindow", "Cadastar Paciente"))
        self.pushButton_controlDiteta.setText(_translate("MainWindow", "Controle de dieta"))
        self.pushButton_registroDieta.setText(_translate("MainWindow", "Registros de dieta"))
        self.pushButton_agenda.setText(_translate("MainWindow", "Agenda"))
